In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
%matplotlib inline
from io import StringIO
import re

In [38]:
for_pd = StringIO()
with open('../data/accre-jobs-2020.csv') as accre:
    for line in accre:
        new_line = re.sub(r',', '|', line.rstrip(), count=12)
        print (new_line, file=for_pd)

for_pd.seek(0)

accre = pd.read_csv(for_pd, sep='|')[1000000:1200000]
print (accre)

            JOBID ACCOUNT      USER   REQMEM    USEDMEM     REQTIME  USEDTIME  \
1000000  18616746     cms  cmslocal   5000Mn   1284.14M  2-00:00:00  00:15:35
1000001  18616752     cms  cmslocal   5000Mn   1275.16M  2-00:00:00  00:11:41
1000002  18616754     cms  cmslocal   5000Mn   1259.60M  2-00:00:00  00:15:35
1000003  18616757     cms  cmslocal   5000Mn   1271.18M  2-00:00:00  00:15:36
1000004  18616758     cms  cmslocal   5000Mn   1260.83M  2-00:00:00  00:15:35
...           ...     ...       ...      ...        ...         ...       ...
1199995  19018067   round   solomon  40960Mn  34678.40M    23:00:00  10:32:23
1199996  19018068   round   solomon  40960Mn  34638.94M    23:00:00  02:15:35
1199997  19018069   round   solomon  40960Mn  34499.11M    23:00:00  05:25:33
1199998  19018070   round   solomon  40960Mn  34817.77M    23:00:00  02:16:56
1199999  19018071   round   solomon  40960Mn  34489.29M    23:00:00  01:50:30

         NODES  CPUS   PARTITION EXITCODE      STATE NODELIST
1000000      1     1  production      0:0  COMPLETED   cn1423
1000001      1     1  production      0:0  COMPLETED   cn1424
1000002      1     1  production      0:0  COMPLETED   cn1311
1000003      1     1  production      0:0  COMPLETED   cn1311
1000004      1     1  production      0:0  COMPLETED    cn372
...        ...   ...         ...      ...        ...      ...
1199995      1     8  production      0:0  COMPLETED   cn1315
1199996      1     8  production      0:0  COMPLETED   cn1371
1199997      1     8  production      0:0  COMPLETED   cn1420
1199998      1     8  production      0:0  COMPLETED   cn1379
1199999      1     8  production      0:0  COMPLETED   cn1404

[200000 rows x 13 columns]

In [39]:
#accre_subset = pd.read_csv('../data/accre-jobs-2020.csv', nrows=5000)
accre.head(20)

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,STATE,NODELIST
1000000,18616746,cms,cmslocal,5000Mn,1284.14M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn1423
1000001,18616752,cms,cmslocal,5000Mn,1275.16M,2-00:00:00,00:11:41,1,1,production,0:0,COMPLETED,cn1424
1000002,18616754,cms,cmslocal,5000Mn,1259.60M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn1311
1000003,18616757,cms,cmslocal,5000Mn,1271.18M,2-00:00:00,00:15:36,1,1,production,0:0,COMPLETED,cn1311
1000004,18616758,cms,cmslocal,5000Mn,1260.83M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn372
1000005,18616762,cms,cmslocal,5000Mn,1258.38M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn361
1000006,18616763,cmsadmin,autocms,2048Mc,828.82M,12:00:00,00:05:08,1,1,production,0:0,COMPLETED,cn1122
1000007,18616858,cms,cmspilot,28000Mn,2846.65M,2-00:00:00,01:12:11,1,4,production,0:0,COMPLETED,cn1299
1000008,18616859,cms,cmspilot,28000Mn,9838.76M,2-00:00:00,1-22:25:09,1,4,production,0:0,COMPLETED,cn1299
1000009,18616860,cms,cmspilot,28000Mn,4915.84M,2-00:00:00,20:12:20,1,4,production,0:0,COMPLETED,cn1356
1000010,18616861,cms,cmspilot,28000Mn,2644.84M,2-00:00:00,00:49:05,1,4,production,0:0,COMPLETED,cn1357
1000011,18616862,cms,cmspilot,28000Mn,9478.09M,2-00:00:00,1-22:58:16,1,4,production,0:0,COMPLETED,cn1384
1000012,18616863,cms,cmspilot,28000Mn,2633.82M,2-00:00:00,07:31:00,1,4,production,0:0,COMPLETED,cn1385
1000013,18616870,cms,cmspilot,186648Mn,69026.19M,2-00:00:00,1-23:23:52,1,32,nogpfs,0:0,COMPLETED,cn1544
1000014,18616871,cms,cmspilot,186648Mn,61206.34M,2-00:00:00,1-23:24:36,1,32,nogpfs,0:0,COMPLETED,cn1573
1000015,18616872,cms,cmspilot,186648Mn,69900.41M,2-00:00:00,1-23:31:03,1,32,nogpfs,0:0,COMPLETED,cn1579
1000016,18616873,cms,cmspilot,21880Mn,1.84M,2-00:00:00,00:21:01,1,8,nogpfs,0:0,COMPLETED,ng502
1000017,18616874,cms,cmspilot,21880Mn,1.82M,2-00:00:00,00:21:01,1,8,nogpfs,0:0,COMPLETED,ng507
1000018,18616875,cms,cmspilot,21880Mn,1.86M,2-00:00:00,00:21:02,1,8,nogpfs,0:0,COMPLETED,ng514
1000019,18616876,cms,cmspilot,46071Mn,13851.20M,2-00:00:00,1-23:13:17,1,8,nogpfs,0:0,COMPLETED,ng671

In [40]:
accre['REQMEM_NO'] = accre['REQMEM'].str.extract('(\d+)')

In [41]:
accre.tail()

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,STATE,NODELIST,REQMEM_NO
1199995,19018067,round,solomon,40960Mn,34678.40M,23:00:00,10:32:23,1,8,production,0:0,COMPLETED,cn1315,40960
1199996,19018068,round,solomon,40960Mn,34638.94M,23:00:00,02:15:35,1,8,production,0:0,COMPLETED,cn1371,40960
1199997,19018069,round,solomon,40960Mn,34499.11M,23:00:00,05:25:33,1,8,production,0:0,COMPLETED,cn1420,40960
1199998,19018070,round,solomon,40960Mn,34817.77M,23:00:00,02:16:56,1,8,production,0:0,COMPLETED,cn1379,40960
1199999,19018071,round,solomon,40960Mn,34489.29M,23:00:00,01:50:30,1,8,production,0:0,COMPLETED,cn1404,40960

In [42]:
accre['REQMEM_TYPE'] = accre['REQMEM'].str.extract('(\D+)')

In [43]:
accre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 1000000 to 1199999
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   JOBID        200000 non-null  object
 1   ACCOUNT      200000 non-null  object
 2   USER         200000 non-null  object
 3   REQMEM       200000 non-null  object
 4   USEDMEM      200000 non-null  object
 5   REQTIME      200000 non-null  object
 6   USEDTIME     200000 non-null  object
 7   NODES        200000 non-null  int64
 8   CPUS         200000 non-null  int64
 9   PARTITION    200000 non-null  object
 10  EXITCODE     200000 non-null  object
 11  STATE        200000 non-null  object
 12  NODELIST     200000 non-null  object
 13  REQMEM_NO    200000 non-null  object
 14  REQMEM_TYPE  200000 non-null  object
dtypes: int64(2), object(13)
memory usage: 22.9+ MB

In [44]:
accre['REQMEM_NO'] = pd.to_numeric(accre['REQMEM_NO'])

In [45]:
accre[accre['REQMEM_TYPE'] == 'Mc']

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,STATE,NODELIST,REQMEM_NO,REQMEM_TYPE
1000006,18616763,cmsadmin,autocms,2048Mc,828.82M,12:00:00,00:05:08,1,1,production,0:0,COMPLETED,cn1122,2048,Mc
1000054,18616942,cmsadmin,autocms,2048Mc,860.54M,12:00:00,00:05:25,1,1,production,0:0,COMPLETED,cn430,2048,Mc
1000165,18617189,pasilla,earlean,3072Mc,197.12M,2-00:00:00,00:03:07,1,10,production,0:15,CANCELLED,cn1459,3072,Mc
1000166,18617190,cmsadmin,autocms,2048Mc,817.76M,12:00:00,00:02:42,1,1,production,0:0,COMPLETED,cn1133,2048,Mc
1000203,18617244_1,casaba,anne,8192Mc,1010.52M,02:30:00,02:30:15,1,1,production,0:0,COMPLETED,cn1335,8192,Mc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1196506,19011073,cmsadmin,autocms,2048Mc,964.95M,12:00:00,00:04:53,1,1,production,0:0,COMPLETED,cn449,2048,Mc
1196711,19014055,cmsadmin,autocms,2048Mc,978.86M,12:00:00,00:05:36,1,1,production,0:0,COMPLETED,cn449,2048,Mc
1196721,19014177,cmsadmin,autocms,2048Mc,942.29M,12:00:00,00:03:24,1,1,production,0:0,COMPLETED,cn449,2048,Mc
1197250,19014859,cmsadmin,autocms,2048Mc,971.62M,12:00:00,00:05:24,1,1,production,0:0,COMPLETED,cn449,2048,Mc
1198819,19016715,cmsadmin,autocms,2048Mc,978.81M,12:00:00,00:04:06,1,1,production,0:0,COMPLETED,cn449,2048,Mc

In [46]:

accre['REQMEM_PER_CORE'] = np.where((accre['REQMEM_TYPE'] == 'Mn'), \
                                      (accre['REQMEM_NO'] * (accre['NODES']/accre['CPUS'])), \
                                       accre['REQMEM_NO'])

accre.head(200)

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,STATE,NODELIST,REQMEM_NO,REQMEM_TYPE,REQMEM_PER_CORE
1000000,18616746,cms,cmslocal,5000Mn,1284.14M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn1423,5000,Mn,5000.000
1000001,18616752,cms,cmslocal,5000Mn,1275.16M,2-00:00:00,00:11:41,1,1,production,0:0,COMPLETED,cn1424,5000,Mn,5000.000
1000002,18616754,cms,cmslocal,5000Mn,1259.60M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn1311,5000,Mn,5000.000
1000003,18616757,cms,cmslocal,5000Mn,1271.18M,2-00:00:00,00:15:36,1,1,production,0:0,COMPLETED,cn1311,5000,Mn,5000.000
1000004,18616758,cms,cmslocal,5000Mn,1260.83M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn372,5000,Mn,5000.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000195,18617243_6,wood,kelly,8192Mn,1076.20M,7-00:00:00,01:35:28,1,1,production,0:0,COMPLETED,cn1426,8192,Mn,8192.000
1000196,18617243_7,wood,kelly,8192Mn,1076.45M,7-00:00:00,01:35:27,1,1,production,0:0,COMPLETED,cn1303,8192,Mn,8192.000
1000197,18617243_8,wood,kelly,8192Mn,1075.65M,7-00:00:00,01:35:28,1,1,production,0:0,COMPLETED,cn1304,8192,Mn,8192.000
1000198,18617243_9,wood,kelly,8192Mn,1075.57M,7-00:00:00,01:35:28,1,1,production,0:0,COMPLETED,cn1345,8192,Mn,8192.000
1000199,18617245,cms,cmslocal,21875Mn,0,2-00:00:00,00:00:03,1,8,nogpfs,0:0,COMPLETED,ng1033,21875,Mn,2734.375

In [47]:
accre['USEDMEM_TYPE'] = accre['USEDMEM'].str.extract('(\D$)')

In [48]:
accre['USEDMEM_NO'] = accre['USEDMEM'].str.extract('(\d+)')

In [49]:
accre['USEDMEM_NO'] = pd.to_numeric(accre['USEDMEM_NO'])

In [50]:
accre['USEDMEM_PER_CORE'] = accre['USEDMEM_NO'] / accre['CPUS']

In [51]:
# test if else logic to convert REQMEM_NO mn's to mc
#test_mn=accre_subset[accre_subset['REQMEM_TYPE']=='Mn'

In [52]:
# accre[accre['REQMEM_TYPE'] == 'Mn']
# test_mc = accre.loc[1000006, 'REQMEM_NO']
# test_mn = accre.loc[1000000,'REQMEM_NO']

In [53]:
# accre[accre['REQMEM_TYPE'] == 'Mn']
# test_mc = accre.loc[1000006, 'REQMEM_NO']
# test_mn = accre.loc[1000000,'REQMEM_NO']
# test_mn = accre.loc[1000000,['REQMEM_NO', 'REQMEM', 'NODES', 'CPUS', 'REQMEM_TYPE']]
# test_mn

In [54]:
# IF REQMEM_TYP = Mn
# REQMEM = REQMEM_NO * (NODES/CPUS)
#test_mn = if REQMEM_TYPE == 'Mn',

In [55]:
# if test_mc['REQMEM_TYPE'] == 'Mc':
#     print(test_mc['REQMEM_NO'])
# elif test_mc['REQMEM_TYPE'] == 'Mn':
#     print(test_mc['REQMEM_NO'] * (test_mc['NODES']/test_mc['CPU']))

In [56]:
accre.head()

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,STATE,NODELIST,REQMEM_NO,REQMEM_TYPE,REQMEM_PER_CORE,USEDMEM_TYPE,USEDMEM_NO,USEDMEM_PER_CORE
1000000,18616746,cms,cmslocal,5000Mn,1284.14M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn1423,5000,Mn,5000.0,M,1284,1284.0
1000001,18616752,cms,cmslocal,5000Mn,1275.16M,2-00:00:00,00:11:41,1,1,production,0:0,COMPLETED,cn1424,5000,Mn,5000.0,M,1275,1275.0
1000002,18616754,cms,cmslocal,5000Mn,1259.60M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn1311,5000,Mn,5000.0,M,1259,1259.0
1000003,18616757,cms,cmslocal,5000Mn,1271.18M,2-00:00:00,00:15:36,1,1,production,0:0,COMPLETED,cn1311,5000,Mn,5000.0,M,1271,1271.0
1000004,18616758,cms,cmslocal,5000Mn,1260.83M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn372,5000,Mn,5000.0,M,1260,1260.0

In [57]:
#convert time to seconds.  First, replace hyphen (day) with :
accre['REQTIME_DAYS'] = accre['REQTIME'].str.extract('(\d+)-')
accre.REQTIME

1000000    2-00:00:00
1000001    2-00:00:00
1000002    2-00:00:00
1000003    2-00:00:00
1000004    2-00:00:00
              ...
1199995      23:00:00
1199996      23:00:00
1199997      23:00:00
1199998      23:00:00
1199999      23:00:00
Name: REQTIME, Length: 200000, dtype: object

In [58]:
#convert time to seconds
#accre['REQTIME'] = pd.to_datetime(accre['REQTIME'])

In [59]:
# can also try when reading in the file, parse_dates=["REQTIME", "TIMEUSED"]

In [60]:
#convert datetime columns to seconds 
# days = int(input("Input days: ")) * 3600 * 24
# hours = int(input("Input hours: ")) * 3600
# minutes = int(input("Input minutes: ")) * 60
# seconds = int(input("Input seconds: "))

# time = days + hours + minutes + seconds

# print("The  amounts of seconds", time)

In [61]:
accre.groupby('STATE').size()

STATE
CANCELLED                 261
CANCELLED by 200557         2
CANCELLED by 782611         1
COMPLETED              199707
FAILED                     23
OUT_OF_MEMORY               5
TIMEOUT                     1
dtype: int64

In [62]:
# review failed nodes, first identify failed jobs
failed = accre[accre['STATE'] == 'FAILED']
failed

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,STATE,NODELIST,REQMEM_NO,REQMEM_TYPE,REQMEM_PER_CORE,USEDMEM_TYPE,USEDMEM_NO,USEDMEM_PER_CORE,REQTIME_DAYS
1028647,18677912,plantain,makala,4096Mn,0.36M,00:30:00,00:00:01,1,8,debug,2:0,FAILED,cn1101,4096,Mn,512.000000,M,0,0.000000,NaN
1028852,18677967,plantain,makala,4096Mn,0.36M,00:30:00,00:00:01,1,8,debug,2:0,FAILED,cn1101,4096,Mn,512.000000,M,0,0.000000,NaN
1033636,18688478,plantain,makala,4096Mn,0,00:30:00,00:00:01,1,12,debug,1:0,FAILED,cn1231,4096,Mn,341.333333,NaN,0,0.000000,NaN
1037292,18696144,turban,hardie,92160Mn,2621.49M,10:00:00,05:29:08,1,1,maxwell,1:0,FAILED,gpu0005,92160,Mn,92160.000000,M,2621,2621.000000,NaN
1060362,18741099,plantain,makala,16384Mn,0,6-00:00:00,00:00:04,1,12,production,1:0,FAILED,cn1366,16384,Mn,1365.333333,NaN,0,0.000000,6
1096606,18798074,turban,hardie,122880Mn,0,10:00:00,00:00:01,2,4,pascal,127:0,FAILED,gpu[0018-0019],122880,Mn,61440.000000,NaN,0,0.000000,NaN
1096669,18798137,turban,hardie,122880Mn,0.08M,10:00:00,00:00:00,2,4,pascal,127:0,FAILED,gpu[0018-0019],122880,Mn,61440.000000,M,0,0.000000,NaN
1096730,18798200,turban,hardie,122880Mn,0,10:00:00,00:00:03,2,4,pascal,127:0,FAILED,gpu[0018-0019],122880,Mn,61440.000000,NaN,0,0.000000,NaN
1128899,18868869,crab,nile,49152Mn,0,01:00:00,00:00:01,1,12,production,2:0,FAILED,cn1526,49152,Mn,4096.000000,NaN,0,0.000000,NaN
1128929,18868999,crab,nile,49152Mn,0,01:00:00,00:00:01,1,12,production,127:0,FAILED,cn1526,49152,Mn,4096.000000,NaN,0,0.000000,NaN
1131099,18873574,crab,nile,32768Mn,0,03:00:00,00:00:01,1,8,production,127:0,FAILED,cn1458,32768,Mn,4096.000000,NaN,0,0.000000,NaN
1131100,18873604,crab,nile,49152Mn,0,03:00:00,00:00:01,1,8,production,127:0,FAILED,cn1486,49152,Mn,6144.000000,NaN,0,0.000000,NaN
1132075,18876596,crab,nile,49152Mn,0,03:00:00,00:00:02,1,8,production,127:0,FAILED,cn1435,49152,Mn,6144.000000,NaN,0,0.000000,NaN
1132553,18877883,tips,ole,20480Mn,1420.07M,05:00:00,00:12:21,2,12,production,1:0,FAILED,cn[1461-1462],20480,Mn,3413.333333,M,1420,118.333333,NaN
1132951,18878719,tips,ole,20480Mn,1525.53M,01:00:00,00:16:48,2,12,production,1:0,FAILED,"cn[1442,1444]",20480,Mn,3413.333333,M,1525,127.083333,NaN
1132962,18878771,tips,ole,20480Mn,1584.22M,05:00:00,00:20:02,1,1,production,1:0,FAILED,cn1267,20480,Mn,20480.000000,M,1584,1584.000000,NaN
1137775,18886004,cubanelle,auther,20480Mn,379.08M,01:00:00,00:13:12,1,1,pascal,6:0,FAILED,gpu0032,20480,Mn,20480.000000,M,379,379.000000,NaN
1142806,18902319,mignonette,hardie,5120Mc,27.41M,05:00:00,00:13:55,13,1,production,1:0,FAILED,"cn[1376-1377,1389-1399]",5120,Mc,5120.000000,M,27,27.000000,NaN
1142965,18902839,mignonette,hardie,5120Mc,46.50M,05:00:00,00:26:16,11,1,production,1:0,FAILED,cn[1389-1399],5120,Mc,5120.000000,M,46,46.000000,NaN
1159041,18924781,tips,ole,20480Mn,2.16M,01:30:00,00:00:13,2,12,production,1:0,FAILED,"cn[1288,1356]",20480,Mn,3413.333333,M,2,0.166667,NaN
1166059,18961240,turban,hardie,122880Mn,1732.48M,10:00:00,00:00:35,1,1,pascal,1:0,FAILED,gpu0016,122880,Mn,122880.000000,M,1732,1732.000000,NaN
1166060,18961258,turban,hardie,122880Mn,3758.34M,20:00:00,15:27:35,1,1,pascal,1:0,FAILED,gpu0016,122880,Mn,122880.000000,M,3758,3758.000000,NaN
1196701,19013255,opo,almond,20480Mn,1537.90M,07:00:00,00:54:33,1,1,maxwell,2:0,FAILED,gpu0010,20480,Mn,20480.000000,M,1537,1537.000000,NaN

In [63]:
accre['REQTIME_DAYS'] = accre['REQTIME_DAYS'].fillna(0)

In [64]:
accre['REQTIME_DAYS'] = accre['REQTIME'].str.extract('(\d+)-')
accre['REQTIME_TOT_DAYS'] = pd.to_numeric(accre['REQTIME_DAYS'])*24

In [65]:
accre.head()

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,...,STATE,NODELIST,REQMEM_NO,REQMEM_TYPE,REQMEM_PER_CORE,USEDMEM_TYPE,USEDMEM_NO,USEDMEM_PER_CORE,REQTIME_DAYS,REQTIME_TOT_DAYS
1000000,18616746,cms,cmslocal,5000Mn,1284.14M,2-00:00:00,00:15:35,1,1,production,...,COMPLETED,cn1423,5000,Mn,5000.0,M,1284,1284.0,2,48.0
1000001,18616752,cms,cmslocal,5000Mn,1275.16M,2-00:00:00,00:11:41,1,1,production,...,COMPLETED,cn1424,5000,Mn,5000.0,M,1275,1275.0,2,48.0
1000002,18616754,cms,cmslocal,5000Mn,1259.60M,2-00:00:00,00:15:35,1,1,production,...,COMPLETED,cn1311,5000,Mn,5000.0,M,1259,1259.0,2,48.0
1000003,18616757,cms,cmslocal,5000Mn,1271.18M,2-00:00:00,00:15:36,1,1,production,...,COMPLETED,cn1311,5000,Mn,5000.0,M,1271,1271.0,2,48.0
1000004,18616758,cms,cmslocal,5000Mn,1260.83M,2-00:00:00,00:15:35,1,1,production,...,COMPLETED,cn372,5000,Mn,5000.0,M,1260,1260.0,2,48.0

In [66]:
from datetime import timedelta

In [67]:
# a_timedelta = accre['TIMEUSED'].timedelta(seconds=24*60*60)

# timedelta_seconds = a_timedelta.total_seconds()

# print(timedelta_seconds)

In [68]:
print(accre.groupby('ACCOUNT')['USER'].count())

ACCOUNT
alkmene        2
almonds        1
anise         18
atemoyas    1432
baking        10
            ...
turban       590
wa             2
water         12
winged         4
wood        2219
Name: USER, Length: 90, dtype: int64

In [69]:
accre.ACCOUNT.describe()

count     200000
unique        90
top          cep
freq       40553
Name: ACCOUNT, dtype: object

In [70]:
cms = accre[accre['ACCOUNT'] == 'cms']
cms

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,...,STATE,NODELIST,REQMEM_NO,REQMEM_TYPE,REQMEM_PER_CORE,USEDMEM_TYPE,USEDMEM_NO,USEDMEM_PER_CORE,REQTIME_DAYS,REQTIME_TOT_DAYS
1000000,18616746,cms,cmslocal,5000Mn,1284.14M,2-00:00:00,00:15:35,1,1,production,...,COMPLETED,cn1423,5000,Mn,5000.00,M,1284,1284.0000,2,48.0
1000001,18616752,cms,cmslocal,5000Mn,1275.16M,2-00:00:00,00:11:41,1,1,production,...,COMPLETED,cn1424,5000,Mn,5000.00,M,1275,1275.0000,2,48.0
1000002,18616754,cms,cmslocal,5000Mn,1259.60M,2-00:00:00,00:15:35,1,1,production,...,COMPLETED,cn1311,5000,Mn,5000.00,M,1259,1259.0000,2,48.0
1000003,18616757,cms,cmslocal,5000Mn,1271.18M,2-00:00:00,00:15:36,1,1,production,...,COMPLETED,cn1311,5000,Mn,5000.00,M,1271,1271.0000,2,48.0
1000004,18616758,cms,cmslocal,5000Mn,1260.83M,2-00:00:00,00:15:35,1,1,production,...,COMPLETED,cn372,5000,Mn,5000.00,M,1260,1260.0000,2,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1196123,19009093,cms,cmspilot,28000Mn,11804.60M,2-00:00:00,1-22:03:30,1,4,production,...,COMPLETED,cn1203,28000,Mn,7000.00,M,11804,2951.0000,2,48.0
1196124,19009094,cms,cmspilot,28000Mn,12967.51M,2-00:00:00,1-22:47:50,1,4,production,...,COMPLETED,cn1281,28000,Mn,7000.00,M,12967,3241.7500,2,48.0
1196197,19009257,cms,cmspilot,28000Mn,21736.27M,2-00:00:00,1-04:12:04,1,4,production,...,COMPLETED,cn1464,28000,Mn,7000.00,M,21736,5434.0000,2,48.0
1196712,19014111,cms,cmspilot,28000Mn,0,2-00:00:00,00:00:12,1,4,production,...,COMPLETED,cn456,28000,Mn,7000.00,NaN,0,0.0000,2,48.0
1196722,19014275,cms,cmspilot,186648Mn,72862.71M,2-00:00:00,1-22:01:45,1,32,nogpfs,...,COMPLETED,cn1586,186648,Mn,5832.75,M,72862,2276.9375,2,48.0

In [71]:
# cms_fail_piv = (accre[accre.ACCOUNT.isin(['cmspilot', 'cmslocal'])]
#                .pivot_table(values = accre[accre['STATE']=='CANCELLED', 'FAILED'], columns = 'NODELIST', index = accre[accre['ACCOUNT'] == 'cms'])
#                .dropna()
#               )

In [72]:
accre[accre["STATE"] == "FAILED"]["NODELIST"].value_counts(sort=True)

gpu[0018-0019]             3
cn1526                     2
gpu0016                    2
cn1101                     2
gpu0005                    1
cn[1442,1444]              1
cn[1389-1399]              1
cn1458                     1
gpu0032                    1
cn1486                     1
cn1366                     1
cn[1461-1462]              1
cn[1288,1356]              1
gpu0010                    1
cn1267                     1
cn1231                     1
cn[1376-1377,1389-1399]    1
cn1435                     1
Name: NODELIST, dtype: int64