In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
%matplotlib inline
from io import StringIO
import re

In [2]:
for_pd = StringIO()
with open('../data/accre-jobs-2020.csv') as accre:
    for line in accre:
        new_line = re.sub(r',', '|', line.rstrip(), count=12)
        print (new_line, file=for_pd)

for_pd.seek(0)

accre_subset = pd.read_csv(for_pd, sep='|')[1000000:1200000]
print (accre_subset)

            JOBID ACCOUNT      USER   REQMEM    USEDMEM     REQTIME  USEDTIME  \
1000000  18616746     cms  cmslocal   5000Mn   1284.14M  2-00:00:00  00:15:35
1000001  18616752     cms  cmslocal   5000Mn   1275.16M  2-00:00:00  00:11:41
1000002  18616754     cms  cmslocal   5000Mn   1259.60M  2-00:00:00  00:15:35
1000003  18616757     cms  cmslocal   5000Mn   1271.18M  2-00:00:00  00:15:36
1000004  18616758     cms  cmslocal   5000Mn   1260.83M  2-00:00:00  00:15:35
...           ...     ...       ...      ...        ...         ...       ...
1199995  19018067   round   solomon  40960Mn  34678.40M    23:00:00  10:32:23
1199996  19018068   round   solomon  40960Mn  34638.94M    23:00:00  02:15:35
1199997  19018069   round   solomon  40960Mn  34499.11M    23:00:00  05:25:33
1199998  19018070   round   solomon  40960Mn  34817.77M    23:00:00  02:16:56
1199999  19018071   round   solomon  40960Mn  34489.29M    23:00:00  01:50:30

         NODES  CPUS   PARTITION EXITCODE      STATE NODELIST
1000000      1     1  production      0:0  COMPLETED   cn1423
1000001      1     1  production      0:0  COMPLETED   cn1424
1000002      1     1  production      0:0  COMPLETED   cn1311
1000003      1     1  production      0:0  COMPLETED   cn1311
1000004      1     1  production      0:0  COMPLETED    cn372
...        ...   ...         ...      ...        ...      ...
1199995      1     8  production      0:0  COMPLETED   cn1315
1199996      1     8  production      0:0  COMPLETED   cn1371
1199997      1     8  production      0:0  COMPLETED   cn1420
1199998      1     8  production      0:0  COMPLETED   cn1379
1199999      1     8  production      0:0  COMPLETED   cn1404

[200000 rows x 13 columns]

In [3]:
#accre_subset = pd.read_csv('../data/accre-jobs-2020.csv', nrows=5000)
accre_subset.head(20)

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,STATE,NODELIST
1000000,18616746,cms,cmslocal,5000Mn,1284.14M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn1423
1000001,18616752,cms,cmslocal,5000Mn,1275.16M,2-00:00:00,00:11:41,1,1,production,0:0,COMPLETED,cn1424
1000002,18616754,cms,cmslocal,5000Mn,1259.60M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn1311
1000003,18616757,cms,cmslocal,5000Mn,1271.18M,2-00:00:00,00:15:36,1,1,production,0:0,COMPLETED,cn1311
1000004,18616758,cms,cmslocal,5000Mn,1260.83M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn372
1000005,18616762,cms,cmslocal,5000Mn,1258.38M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn361
1000006,18616763,cmsadmin,autocms,2048Mc,828.82M,12:00:00,00:05:08,1,1,production,0:0,COMPLETED,cn1122
1000007,18616858,cms,cmspilot,28000Mn,2846.65M,2-00:00:00,01:12:11,1,4,production,0:0,COMPLETED,cn1299
1000008,18616859,cms,cmspilot,28000Mn,9838.76M,2-00:00:00,1-22:25:09,1,4,production,0:0,COMPLETED,cn1299
1000009,18616860,cms,cmspilot,28000Mn,4915.84M,2-00:00:00,20:12:20,1,4,production,0:0,COMPLETED,cn1356
1000010,18616861,cms,cmspilot,28000Mn,2644.84M,2-00:00:00,00:49:05,1,4,production,0:0,COMPLETED,cn1357
1000011,18616862,cms,cmspilot,28000Mn,9478.09M,2-00:00:00,1-22:58:16,1,4,production,0:0,COMPLETED,cn1384
1000012,18616863,cms,cmspilot,28000Mn,2633.82M,2-00:00:00,07:31:00,1,4,production,0:0,COMPLETED,cn1385
1000013,18616870,cms,cmspilot,186648Mn,69026.19M,2-00:00:00,1-23:23:52,1,32,nogpfs,0:0,COMPLETED,cn1544
1000014,18616871,cms,cmspilot,186648Mn,61206.34M,2-00:00:00,1-23:24:36,1,32,nogpfs,0:0,COMPLETED,cn1573
1000015,18616872,cms,cmspilot,186648Mn,69900.41M,2-00:00:00,1-23:31:03,1,32,nogpfs,0:0,COMPLETED,cn1579
1000016,18616873,cms,cmspilot,21880Mn,1.84M,2-00:00:00,00:21:01,1,8,nogpfs,0:0,COMPLETED,ng502
1000017,18616874,cms,cmspilot,21880Mn,1.82M,2-00:00:00,00:21:01,1,8,nogpfs,0:0,COMPLETED,ng507
1000018,18616875,cms,cmspilot,21880Mn,1.86M,2-00:00:00,00:21:02,1,8,nogpfs,0:0,COMPLETED,ng514
1000019,18616876,cms,cmspilot,46071Mn,13851.20M,2-00:00:00,1-23:13:17,1,8,nogpfs,0:0,COMPLETED,ng671

In [4]:
accre_subset['REQMEM_NO']='REQMEM'.split

In [5]:
test_split=accre_subset.loc[1000000,'REQMEM']
test_split

'5000Mn'

In [8]:
re.findall(r"\d+",test_split)

['5000']

In [11]:
re.findall(r"\D+",test_split)

['Mn']

In [16]:
re.findall(r"..$", test_split)

['Mn']

In [17]:
accre_subset['REQMEM_NO'] = accre_subset['REQMEM'].str.extract('(\d+)')

In [18]:
accre_subset.tail()

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,STATE,NODELIST,REQMEM_NO
1199995,19018067,round,solomon,40960Mn,34678.40M,23:00:00,10:32:23,1,8,production,0:0,COMPLETED,cn1315,40960
1199996,19018068,round,solomon,40960Mn,34638.94M,23:00:00,02:15:35,1,8,production,0:0,COMPLETED,cn1371,40960
1199997,19018069,round,solomon,40960Mn,34499.11M,23:00:00,05:25:33,1,8,production,0:0,COMPLETED,cn1420,40960
1199998,19018070,round,solomon,40960Mn,34817.77M,23:00:00,02:16:56,1,8,production,0:0,COMPLETED,cn1379,40960
1199999,19018071,round,solomon,40960Mn,34489.29M,23:00:00,01:50:30,1,8,production,0:0,COMPLETED,cn1404,40960

In [19]:
accre_subset['REQMEM_TYPE'] = accre_subset['REQMEM'].str.extract('(\D+)')

In [20]:
accre_subset.tail()

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,STATE,NODELIST,REQMEM_NO,REQMEM_TYPE
1199995,19018067,round,solomon,40960Mn,34678.40M,23:00:00,10:32:23,1,8,production,0:0,COMPLETED,cn1315,40960,Mn
1199996,19018068,round,solomon,40960Mn,34638.94M,23:00:00,02:15:35,1,8,production,0:0,COMPLETED,cn1371,40960,Mn
1199997,19018069,round,solomon,40960Mn,34499.11M,23:00:00,05:25:33,1,8,production,0:0,COMPLETED,cn1420,40960,Mn
1199998,19018070,round,solomon,40960Mn,34817.77M,23:00:00,02:16:56,1,8,production,0:0,COMPLETED,cn1379,40960,Mn
1199999,19018071,round,solomon,40960Mn,34489.29M,23:00:00,01:50:30,1,8,production,0:0,COMPLETED,cn1404,40960,Mn

In [23]:
accre_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 1000000 to 1199999
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   JOBID        200000 non-null  object
 1   ACCOUNT      200000 non-null  object
 2   USER         200000 non-null  object
 3   REQMEM       200000 non-null  object
 4   USEDMEM      200000 non-null  object
 5   REQTIME      200000 non-null  object
 6   USEDTIME     200000 non-null  object
 7   NODES        200000 non-null  int64
 8   CPUS         200000 non-null  int64
 9   PARTITION    200000 non-null  object
 10  EXITCODE     200000 non-null  object
 11  STATE        200000 non-null  object
 12  NODELIST     200000 non-null  object
 13  REQMEM_NO    200000 non-null  object
 14  REQMEM_TYPE  200000 non-null  object
dtypes: int64(2), object(13)
memory usage: 22.9+ MB

In [26]:
pd.to_numeric(accre_subset['REQMEM_NO'])

1000000     5000
1000001     5000
1000002     5000
1000003     5000
1000004     5000
           ...
1199995    40960
1199996    40960
1199997    40960
1199998    40960
1199999    40960
Name: REQMEM_NO, Length: 200000, dtype: int64

In [31]:
# test if else logic to convert REQMEM_NO mn's to mc
#test_mn=accre_subset[accre_subset['REQMEM_TYPE']=='Mn'

In [34]:
accre_subset[accre_subset['REQMEM_TYPE'] == 'Mn']
test_mc = accre_subset.loc[1000006, 'REQMEM_NO']
test_mn = accre_subset.loc[1000000,'REQMEM_NO']

In [35]:
accre_subset[accre_subset['REQMEM_TYPE'] == 'Mn']
test_mc = accre_subset.loc[1000006, 'REQMEM_NO']
test_mn = accre_subset.loc[1000000,'REQMEM_NO']
test_mn = accre_subset.loc[1000000,['REQMEM_NO', 'REQMEM', 'NODES', 'CPUS', 'REQMEM_TYPE']]
test_mn

REQMEM_NO        5000
REQMEM         5000Mn
NODES               1
CPUS                1
REQMEM_TYPE        Mn
Name: 1000000, dtype: object

In [ ]:
# IF REQMEM_TYP = Mn
# REQMEM = REQMEM_NO * (NODES/CPUS)
test_mn = if REQMEM_TYPE == 'Mn',

In [ ]:
if test_mc['REQMEM_TYPE'] == 'Mc':
    print(test_mc['REQMEM_NO'])
elif test_mc['REQMEM_TYPE'] == 'Mn':
    print(test_mc['REQMEM_NO'] * (test_mc['NODES']/test_mc['CPU']))

In [32]:
test_mn.head()

,JOBID,ACCOUNT,USER,REQMEM,USEDMEM,REQTIME,USEDTIME,NODES,CPUS,PARTITION,EXITCODE,STATE,NODELIST,REQMEM_NO,REQMEM_TYPE
1000000,18616746,cms,cmslocal,5000Mn,1284.14M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn1423,5000,Mn
1000001,18616752,cms,cmslocal,5000Mn,1275.16M,2-00:00:00,00:11:41,1,1,production,0:0,COMPLETED,cn1424,5000,Mn
1000002,18616754,cms,cmslocal,5000Mn,1259.60M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn1311,5000,Mn
1000003,18616757,cms,cmslocal,5000Mn,1271.18M,2-00:00:00,00:15:36,1,1,production,0:0,COMPLETED,cn1311,5000,Mn
1000004,18616758,cms,cmslocal,5000Mn,1260.83M,2-00:00:00,00:15:35,1,1,production,0:0,COMPLETED,cn372,5000,Mn

In [ ]:
test_cvt

In [ ]:
accre_subset.info()

In [ ]:
accre_subset.describe()

In [ ]:
accre_subset['STATE'].describe()

In [ ]:
accre_subset['STATE'].value_counts()

In [13]:
accre_subset['USEDMEM'].describe()

count     200000
unique     87262
top            0
freq       36936
Name: USEDMEM, dtype: object

In [12]:
accre_subset['USEDMEM'].value_counts()

0            36936
0.09M         2989
1.16M         2442
1.17M         1921
1.82M         1607
             ...
5152.77M         1
15561.97M        1
118.94M          1
383.75M          1
6233.68M         1
Name: USEDMEM, Length: 87262, dtype: int64

In [15]:
accre_subset['REQMEM'].describe()

count      200000
unique         88
top       16384Mn
freq        50774
Name: REQMEM, dtype: object

In [ ]:
accre_subset['EXITCODE'].value_counts()

In [ ]:
accre_subset['NODELIST'].value_counts()

In [28]:
accre_subset['REQMEM_TYPE'].value_counts()

Mn    146190
Mc     53810
Name: REQMEM_TYPE, dtype: int64

In [29]:
accre_subset['REQMEM_TYPE'].unique()

array(['Mn', 'Mc'], dtype=object)